version: '3'

services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
          - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
          ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
          ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/

    redis:
        image: 'bitnami/redis:latest'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - 6379:6379

    rss_updater:
        build: .
        image: wancheez/rss_reader:1
        command: sh -c "dramatiq rss_reader.service_layer.update_service"
        restart: always
        depends_on:
          - redis
          - mongo

    rss_reader:
        image: wancheez/rss_reader:1
        command: sh -c "uvicorn entrypoints.fastapi.fastapi_app:app --log-config=conf/logging.yaml --host 0.0.0.0 --port 8000"
        restart: always
        depends_on:
          - redis
          - mongo
          - rss_updater
        stdin_open: true
        tty: true
        ports:
        - "8000:8000"